# version: 1.0.0

add_newline = false
continuation_prompt = "[ ▸▹ ](dimmed white)"

format = """($nix_shell$container$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$custom_branch_count\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$tmux\
$status\
$os\
$custom_tmux\
$battery\
$time"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[ 󰗠 ](bold italic bright-green)"
error_symbol = "[ 󰅙 ](italic bright-red)"
vimcmd_symbol = "[  ](italic dimmed green)"
vimcmd_replace_one_symbol = "󰬲 "
vimcmd_replace_symbol = "󰛔 "
vimcmd_visual_symbol = "󰒉 "

[env_var.VIMSHELL]
format = "[ $env_value]($style)"
style = 'green italic'

[sudo]
format = "[ $symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[ ⭘ $user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = "󱂵 "
truncation_length = 2
truncation_symbol = "󰅂"
read_only = " 󰌾"
use_os_path_sep = true
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [󰊢](bold bright-blue)'

[cmd_duration]
min_time = 0
format = "[ ◄ $duration ](italic white)"

[jobs]
format = "[ $symbol$number]($style) "
style = "white"
symbol = "[ 󰝨](blue italic)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[time]
disabled = false
format = "[ 󰥔 $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed white"

[battery]
format = "[  $percentage $symbol]($style)"
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
unknown_symbol = " "
empty_symbol = " "

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

[[battery.display]]
threshold = 100
style = "italic dimmed green"

[git_branch]
format = "  [$branch]($style)"
symbol = ""
style = "italic bright-blue"
truncation_symbol = "󰅂"
truncation_length = 20
only_attached = true
always_show_remote = true

[git_state]
rebase = "󰊢 REBASING"
merge = "󰊢 MERGING"
revert = "󰊢 REVERTING"
cherry_pick = "󰊢 CHERRY-PICKING"
bisect = "󰊢 BISECTING"
am = "󰊢 APPLYING MAILBOX"
am_or_rebase = "󰊢 AM/REBASE"
style = "bold italic bright-yellow"
format = "([$state( $progress_current/$progress_total)]($style)) "
disabled = false

[custom.branch_count]
command = "git branch --all | grep -v '/HEAD' | wc -l | tr -d ' '"
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
format = "[ 󰊤 $output]($style)"
style = "italic dimmed blue"

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic bright-blue"
format = "([$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed]($style))"
conflicted = "[ 󰈸](italic bright-magenta)"
ahead = "[ ${count}](italic green)"
behind = "[ ${count}](italic red)"
diverged = "[  ▴${ahead_count}▿${behind_count}](italic bright-magenta)"
stashed = "[ ](italic white)"
modified = "[ ](italic yellow)"
staged = "[  ${count}](italic bright-cyan)"
renamed = "[ ](italic bright-blue)"
deleted = "[ ](italic red)"
untracked = "[ ?](italic white)"

[deno]
format = "[  deno](italic)[ 󰠱 $version](green bold)"
version_format = "${raw}"

[lua]
format = "[ 󰢱 lua](bold bright-yellow)[ $version]($style)"
version_format = "${raw}"

[nodejs]
format = "[ 󰎙 node](italic)[ 󰠱 $version](bold bright-green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock", "package.json", "pnpm-lock.yaml"]
detect_folders = ["node_modules"]

[python]
format = "[ 󰌠 py](italic)[ $version](bold bright-yellow)"
version_format = "${raw}"

[ruby]
format = "[ 󰴭 rb](italic)[ $version](bold red)"
version_format = "${raw}"

[rust]
format = "[ 󱘗 rs](italic)[ $version](bold red)"
version_format = "${raw}"

[package]
format = "[ 󰏓 pkg](italic dimmed)[ $version](dimmed yellow italic bold)"
version_format = "${raw}"

[swift]
format = "[ 󰛥 sw](italic)[ $version](bold bright-red)"
version_format = "${raw}"

[aws]
disabled = true
format = "[  aws](italic)[ $profile $region](bold blue)"

[buf]
symbol = "󰕸"
format = "[ $symbol buf](italic)[ $version]($style)"

[c]
symbol = "󰙱"
format = "[ $symbol c]($style)[ $version]($style)"

[conda]
symbol = ""
format = "[ $symbol conda]($style)[ $environment]($style)"

[dart]
symbol = ""
format = "[ $symbol dart]($style)[ $version]($style)"

[docker_context]
symbol = "󰡨"
format = "[ $symbol docker]($style)[ $context]($style)"

[elixir]
symbol = ""
format = "[ $symbol elixir]($style)[ $version]($style)"

[elm]
symbol = ""
format = "[ $symbol elm]($style)[ $version]($style)"

[golang]
symbol = ""
format = "[ $symbol go]($style)[ $version]($style)"

[haskell]
symbol = "󰲒"
format = "[ $symbol haskell]($style)[ $version]($style)"

[java]
symbol = ""
format = "[ $symbol java]($style)[ $version]($style)"

[julia]
symbol = ""
format = "[ $symbol julia]($style)[ $version]($style)"

[memory_usage]
disabled = false
symbol = "󰍛"
format = "[ $symbol mem]($style)[ $ram]($style)"

[nim]
symbol = ""
format = "[ $symbol nim]($style)[ $version]($style)"

[nix_shell]
style = 'bold italic dimmed blue'
symbol = ''
format = '[$symbol nix]($style)[ $state]($style)[ $name](italic dimmed white)'
impure_msg = ''
pure_msg = '󰅺'
unknown_msg = '󰠗'

[spack]
symbol = "󰌹"
format = "[ $symbol spack]($style)[ $environment]($style)"

[custom.tmux]
command = "echo -n "
when = "env | grep -q TMUX"
format = "[ $output]($style)"
style = "bold bright-purple"
disabled = false
